server:
  port: 8080

routes:
  - path: "/api/v1/users"
    target: "http://:3000"
    protected: true # Requer autenticação
    rate_limit: 100

  - path: "/api/v1/posts"
    target: "http://:8081"
    protected: false # vai ser um serviço público
    rate_limit: 50
